/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pizzaria.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import pizzaria.Pizzaria;
import pizzaria.forma.Circle;
import pizzaria.model.Client;

/**
 *
 * @author Vinicius Dias
 */
public class makeOrder extends javax.swing.JPanel {

    private ArrayList<Client> clientList;
    private Pizzaria sistema;
    private javax.swing.JPanel lastScreen;
    private Client selectedClient;
    private double orderArea;
    /**
     * Creates new form makeOrder
     */
    public makeOrder(Pizzaria sistema, javax.swing.JPanel lastScreen, Client selectedClient) {
        initComponents();
        this.sistema = sistema;
        this.clientList = sistema.getClients();
        this.lastScreen = lastScreen;
        this.selectedClient = selectedClient;

        jTextField2.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { atualizarArea(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { atualizarArea(); }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { atualizarArea(); }
        });

        jTextField2.setText("0");
        jComboBox1ActionPerformed(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Fazer Pedido");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quadrado", "Círculo", "Triângulo" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel2.setText("Formato Desejado:");

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Prosseguir");
        jButton1.setToolTipText("Prosseguir para sabor");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setLabel("Cancelar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Inicio");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel3.setText("Dimensão (cm)");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel4.setText("Área:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 255, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(259, 259, 259))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(284, 284, 284))))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        javax.swing.JFrame lastWindow = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        lastWindow.setContentPane(lastScreen);
        lastWindow.revalidate();
        lastWindow.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SignupClient signupScreen = new SignupClient(this.sistema, -1, this); //-1 é para cadastro de cliente e this é referente ao painel atual
        javax.swing.JFrame janelaPrincipal = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        janelaPrincipal.setContentPane(signupScreen);
        janelaPrincipal.revalidate();
        janelaPrincipal.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dimensionText = jTextField2.getText().replace(",", ".");        
        try {
            double dimension = Double.parseDouble(dimensionText);
            if (dimension <= 0) {
                JOptionPane.showMessageDialog(this, "A dimensão deve ser maior que 0 para prosseguir com o pedido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido para a dimensão!", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String format = jComboBox1.getSelectedItem().toString();
        ListAvaliableFlavors flavorsScreen = new ListAvaliableFlavors(this, format, this.sistema, this.selectedClient, jTextField2.getText());
        
        javax.swing.JFrame mainScreen = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        mainScreen.setContentPane(flavorsScreen);  
        mainScreen.revalidate();
        mainScreen.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String format = jComboBox1.getSelectedItem().toString();
        double formatDefault = 0;

        switch (format){
            case "Círculo":
                formatDefault = 7.0; //raio min
                jLabel3.setText("Raio (7 - 23cm):");
                break;
            case "Triângulo":
                formatDefault = 20.0;
                jLabel3.setText("Lado (20 - 60 cm):");
                break;
            case "Quadrado":
                formatDefault = 10.0;
                jLabel3.setText("Lado (10 - 40 cm):");
                break;
            default:
                jLabel3.setText("Dimensão(cm):");
        }

        jTextField2.setText(String.valueOf(formatDefault));    
        atualizarArea();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void atualizarArea() {
        try {
            String format = jComboBox1.getSelectedItem().toString();
            String dimensionText = jTextField2.getText().replace(",", ".");
            if (dimensionText.trim().isEmpty()) {
                jLabel4.setText("Área (cm 2): 0.00");
                return;
            }

            double dimension = Double.parseDouble(dimensionText);
            double area = 0.0;

            switch (format) {
                case "Círculo":
                    area = Math.PI * Math.pow(dimension, 2);
                    break;
                case "Triângulo":
                    area = (Math.pow(dimension, 2) * Math.sqrt(3)) / 4.0;
                    break;
                case "Quadrado":
                    area = Math.pow(dimension, 2);
                    break;
            }

            jLabel4.setText("Área (cm 2): " + String.format("%.2f", area));

        } catch (NumberFormatException e) {
            jLabel4.setText("Área (cm 2): Valor Inválido");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
